'use client';

import CategoryProducts from './CategoryProducts';

const categories = [
  {
    id: 'ao-thun',
    title: 'Áo Thun Nổi Bật',
    products: [
      {
        id: "1",
        name: "Áo Polo Thể Thao Pro Active 1595 Phối Màu",
        image: "/images/thun.jpg",
        price: 249000,
        oldPrice: null,
        discount: null,
        rating: 4.9,
        reviews: 38,
        label: "ĐÁNG MUA",
        colors: [
          { code: "#222", name: "Đen" },
          { code: "#fff", name: "Trắng" },
          { code: "#bdbdbd", name: "Xám" },
        ],
      },
      {
        id: "2",
        name: "Pack 3 Áo Polo nam Pique Cotton",
        image: "/images/thun.jpg",
        price: 759000,
        oldPrice: 897000,
        discount: 15,
        rating: 4.8,
        reviews: 284,
        label: "SAVING PACKS",
        colors: [
          { code: "#795548", name: "Nâu" },
          { code: "#f5f5dc", name: "Be" },
          { code: "#222", name: "Đen" },
        ],
      },
      {
        id: "3",
        name: "Áo Polo Nam Ice Cooling",
        image: "/images/thun.jpg",
        price: 299000,
        oldPrice: 349000,
        discount: 14,
        rating: 4.9,
        reviews: 32,
        label: null,
        colors: [
          { code: "#90caf9", name: "Xanh nhạt" },
          { code: "#fff", name: "Trắng" },
        ],
      },
      {
        id: "4",
        name: "Áo Polo Nam Pique Cotton USA",
        image: "/images/thun.jpg",
        price: 149000,
        oldPrice: 399000,
        discount: 63,
        rating: 4.9,
        reviews: 170,
        label: "OUTLET",
        colors: [
          { code: "#789262", name: "Xanh rêu" },
          { code: "#222", name: "Đen" },
        ],
      },
      {
        id: "5",
        name: "Áo Polo Nam Pique Cotton",
        image: "/images/thun.jpg",
        price: 259000,
        oldPrice: 299000,
        discount: 13,
        rating: 4.8,
        reviews: 284,
        label: "ĐÁNG MUA",
        colors: [
          { code: "#795548", name: "Nâu" },
          { code: "#f5f5dc", name: "Be" },
          { code: "#222", name: "Đen" },
        ],
      },
      {
        id: "6",
        name: "Polo thể thao nam Promax Sideflow",
        image: "/images/thun.jpg",
        price: 249000,
        oldPrice: null,
        discount: null,
        rating: 4.8,
        reviews: 284,
        label: "NEW",
        colors: [
          { code: "#222", name: "Đen" },
          { code: "#fff", name: "Trắng" },
        ],
      },
      {
        id: "7",
        name: "Áo Polo thể thao Graphene",
        image: "/images/thun.jpg",
        price: 279000,
        oldPrice: null,
        discount: null,
        rating: 4.8,
        reviews: 284,
        label: null,
        colors: [
          { code: "#bdbdbd", name: "Xám" },
          { code: "#222", name: "Đen" },
        ],
      },
      {
        id: "8",
        name: "Áo Polo Nam Cafe Essentials",
        image: "/images/thun.jpg",
        price: 269000,
        oldPrice: 299000,
        discount: 10,
        rating: 4.9,
        reviews: 56,
        label: "OUTLET",
        colors: [
          { code: "#222", name: "Đen" },
          { code: "#fff", name: "Trắng" },
        ],
      },
      {
        id: "9",
        name: "Áo Polo Nam Sport Premium",
        image: "/images/thun.jpg",
        price: 289000,
        oldPrice: 329000,
        discount: 12,
        rating: 4.9,
        reviews: 92,
        label: "NEW",
        colors: [
          { code: "#222", name: "Đen" },
          { code: "#fff", name: "Trắng" },
          { code: "#bdbdbd", name: "Xám" },
        ],
      },
      {
        id: "10",
        name: "Áo Polo Nam Active Pro",
        image: "/images/thun.jpg",
        price: 299000,
        oldPrice: 349000,
        discount: 14,
        rating: 4.8,
        reviews: 78,
        label: "ĐÁNG MUA",
        colors: [
          { code: "#222", name: "Đen" },
          { code: "#fff", name: "Trắng" },
        ],
      },
      {
        id: "11",
        name: "Áo Polo Nam Classic Fit",
        image: "/images/thun.jpg",
        price: 259000,
        oldPrice: 299000,
        discount: 13,
        rating: 4.7,
        reviews: 45,
        label: null,
        colors: [
          { code: "#795548", name: "Nâu" },
          { code: "#f5f5dc", name: "Be" },
        ],
      },
      {
        id: "12",
        name: "Áo Polo Nam Slim Fit",
        image: "/images/thun.jpg",
        price: 279000,
        oldPrice: 319000,
        discount: 13,
        rating: 4.9,
        reviews: 156,
        label: "OUTLET",
        colors: [
          { code: "#222", name: "Đen" },
          { code: "#fff", name: "Trắng" },
          { code: "#bdbdbd", name: "Xám" },
        ],
      },
      {
        id: "13",
        name: "Áo Polo Nam Performance",
        image: "/images/thun.jpg",
        price: 309000,
        oldPrice: 359000,
        discount: 14,
        rating: 4.8,
        reviews: 89,
        label: "NEW",
        colors: [
          { code: "#222", name: "Đen" },
          { code: "#fff", name: "Trắng" },
        ],
      },
    ]
  },
  {
    id: 'quan-short',
    title: 'Quần Short Bán Chạy',
    products: [
      {
        id: "quan-short-1",
        name: "Quần Short Nam Thể Thao",
        image: "/images/nam-quan-short.jpg",
        price: 179000,
        oldPrice: 199000,
        discount: 10,
        rating: 4.7,
        reviews: 45,
        label: "NEW",
        colors: [
          { code: "#222", name: "Đen" },
          { code: "#bdbdbd", name: "Xám" },
        ],
      },
      {
        id: "quan-short-2",
        name: "Quần Short Nam Gym",
        image: "/images/nam-quan-short.jpg",
        price: 219000,
        oldPrice: 249000,
        discount: 12,
        rating: 4.8,
        reviews: 89,
        label: "ĐÁNG MUA",
        colors: [
          { code: "#222", name: "Đen" },
          { code: "#fff", name: "Trắng" },
        ],
      },
      {
        id: "quan-short-3",
        name: "Quần Short Nam Chạy Bộ",
        image: "/images/nam-quan-short.jpg",
        price: 199000,
        oldPrice: null,
        discount: null,
        rating: 4.6,
        reviews: 32,
        label: null,
        colors: [
          { code: "#222", name: "Đen" },
          { code: "#bdbdbd", name: "Xám" },
        ],
      },
      {
        id: "quan-short-4",
        name: "Quần Short Nam Casual",
        image: "/images/nam-quan-short.jpg",
        price: 159000,
        oldPrice: 199000,
        discount: 20,
        rating: 4.9,
        reviews: 156,
        label: "OUTLET",
        colors: [
          { code: "#222", name: "Đen" },
          { code: "#fff", name: "Trắng" },
        ],
      },
      {
        id: "quan-short-5",
        name: "Quần Short Nam Thể Thao Pro",
        image: "/images/nam-quan-short.jpg",
        price: 189000,
        oldPrice: 229000,
        discount: 17,
        rating: 4.8,
        reviews: 78,
        label: "NEW",
        colors: [
          { code: "#222", name: "Đen" },
          { code: "#bdbdbd", name: "Xám" },
        ],
      },
      {
        id: "quan-short-6",
        name: "Quần Short Nam Gym Premium",
        image: "/images/nam-quan-short.jpg",
        price: 239000,
        oldPrice: 279000,
        discount: 14,
        rating: 4.9,
        reviews: 92,
        label: "ĐÁNG MUA",
        colors: [
          { code: "#222", name: "Đen" },
          { code: "#fff", name: "Trắng" },
        ],
      },
      {
        id: "quan-short-7",
        name: "Quần Short Nam Chạy Bộ Pro",
        image: "/images/nam-quan-short.jpg",
        price: 209000,
        oldPrice: null,
        discount: null,
        rating: 4.7,
        reviews: 45,
        label: null,
        colors: [
          { code: "#222", name: "Đen" },
          { code: "#bdbdbd", name: "Xám" },
        ],
      },
      {
        id: "quan-short-8",
        name: "Quần Short Nam Casual Premium",
        image: "/images/nam-quan-short.jpg",
        price: 169000,
        oldPrice: 199000,
        discount: 15,
        rating: 4.8,
        reviews: 134,
        label: "OUTLET",
        colors: [
          { code: "#222", name: "Đen" },
          { code: "#fff", name: "Trắng" },
        ],
      },
    ]
  },
  {
    id: 'do-boi',
    title: 'Đồ Bơi Mới Về',
    products: [
      {
        id: "do-boi-1",
        name: "Quần Bơi Nam Thể Thao",
        image: "/images/nam-do-boi.jpg",
        price: 159000,
        oldPrice: 199000,
        discount: 20,
        rating: 4.8,
        reviews: 67,
        label: "NEW",
        colors: [
          { code: "#222", name: "Đen" },
          { code: "#1976d2", name: "Xanh dương" },
        ],
      },
      {
        id: "do-boi-2",
        name: "Quần Bơi Nam Gym",
        image: "/images/nam-do-boi.jpg",
        price: 189000,
        oldPrice: 229000,
        discount: 17,
        rating: 4.7,
        reviews: 45,
        label: "ĐÁNG MUA",
        colors: [
          { code: "#222", name: "Đen" },
          { code: "#1976d2", name: "Xanh dương" },
        ],
      },
      {
        id: "do-boi-3",
        name: "Quần Bơi Nam Chuyên Nghiệp",
        image: "/images/nam-do-boi.jpg",
        price: 219000,
        oldPrice: null,
        discount: null,
        rating: 4.9,
        reviews: 89,
        label: null,
        colors: [
          { code: "#222", name: "Đen" },
          { code: "#1976d2", name: "Xanh dương" },
        ],
      },
      {
        id: "do-boi-4",
        name: "Quần Bơi Nam Casual",
        image: "/images/nam-do-boi.jpg",
        price: 139000,
        oldPrice: 179000,
        discount: 22,
        rating: 4.6,
        reviews: 34,
        label: "OUTLET",
        colors: [
          { code: "#222", name: "Đen" },
          { code: "#1976d2", name: "Xanh dương" },
        ],
      },
      {
        id: "do-boi-5",
        name: "Quần Bơi Nam Thể Thao Pro",
        image: "/images/nam-do-boi.jpg",
        price: 179000,
        oldPrice: 219000,
        discount: 18,
        rating: 4.9,
        reviews: 78,
        label: "NEW",
        colors: [
          { code: "#222", name: "Đen" },
          { code: "#1976d2", name: "Xanh dương" },
        ],
      },
      {
        id: "do-boi-6",
        name: "Quần Bơi Nam Gym Premium",
        image: "/images/nam-do-boi.jpg",
        price: 209000,
        oldPrice: 249000,
        discount: 16,
        rating: 4.8,
        reviews: 92,
        label: "ĐÁNG MUA",
        colors: [
          { code: "#222", name: "Đen" },
          { code: "#1976d2", name: "Xanh dương" },
        ],
      },
      {
        id: "do-boi-7",
        name: "Quần Bơi Nam Chuyên Nghiệp Pro",
        image: "/images/nam-do-boi.jpg",
        price: 239000,
        oldPrice: null,
        discount: null,
        rating: 4.9,
        reviews: 67,
        label: null,
        colors: [
          { code: "#222", name: "Đen" },
          { code: "#1976d2", name: "Xanh dương" },
        ],
      },
      {
        id: "do-boi-8",
        name: "Quần Bơi Nam Casual Premium",
        image: "/images/nam-do-boi.jpg",
        price: 149000,
        oldPrice: 189000,
        discount: 21,
        rating: 4.7,
        reviews: 45,
        label: "OUTLET",
        colors: [
          { code: "#222", name: "Đen" },
          { code: "#1976d2", name: "Xanh dương" },
        ],
      },
    ]
  },
  {
    id: 'ao-polo',
    title: 'Áo Polo Mới Về',
    products: [
      {
        id: "ao-polo-1",
        name: "Áo Polo Nam Thể Thao",
        image: "/images/nam-ao-polo.jpg",
        price: 259000,
        oldPrice: 299000,
        discount: 13,
        rating: 4.8,
        reviews: 89,
        label: "NEW",
        colors: [
          { code: "#222", name: "Đen" },
          { code: "#fff", name: "Trắng" },
        ],
      },
      {
        id: "ao-polo-2",
        name: "Áo Polo Nam Gym",
        image: "/images/nam-ao-polo.jpg",
        price: 289000,
        oldPrice: 329000,
        discount: 12,
        rating: 4.9,
        reviews: 156,
        label: "ĐÁNG MUA",
        colors: [
          { code: "#222", name: "Đen" },
          { code: "#fff", name: "Trắng" },
        ],
      },
      {
        id: "ao-polo-3",
        name: "Áo Polo Nam Chạy Bộ",
        image: "/images/nam-ao-polo.jpg",
        price: 269000,
        oldPrice: null,
        discount: null,
        rating: 4.7,
        reviews: 67,
        label: null,
        colors: [
          { code: "#222", name: "Đen" },
          { code: "#fff", name: "Trắng" },
        ],
      },
      {
        id: "ao-polo-4",
        name: "Áo Polo Nam Casual",
        image: "/images/nam-ao-polo.jpg",
        price: 229000,
        oldPrice: 269000,
        discount: 15,
        rating: 4.8,
        reviews: 134,
        label: "OUTLET",
        colors: [
          { code: "#222", name: "Đen" },
          { code: "#fff", name: "Trắng" },
        ],
      },
      {
        id: "ao-polo-5",
        name: "Áo Polo Nam Thể Thao Pro",
        image: "/images/nam-ao-polo.jpg",
        price: 279000,
        oldPrice: 319000,
        discount: 13,
        rating: 4.9,
        reviews: 92,
        label: "NEW",
        colors: [
          { code: "#222", name: "Đen" },
          { code: "#fff", name: "Trắng" },
        ],
      },
      {
        id: "ao-polo-6",
        name: "Áo Polo Nam Gym Premium",
        image: "/images/nam-ao-polo.jpg",
        price: 309000,
        oldPrice: 349000,
        discount: 11,
        rating: 4.8,
        reviews: 178,
        label: "ĐÁNG MUA",
        colors: [
          { code: "#222", name: "Đen" },
          { code: "#fff", name: "Trắng" },
        ],
      },
      {
        id: "ao-polo-7",
        name: "Áo Polo Nam Chạy Bộ Pro",
        image: "/images/nam-ao-polo.jpg",
        price: 289000,
        oldPrice: null,
        discount: null,
        rating: 4.7,
        reviews: 89,
        label: null,
        colors: [
          { code: "#222", name: "Đen" },
          { code: "#fff", name: "Trắng" },
        ],
      },
      {
        id: "ao-polo-8",
        name: "Áo Polo Nam Casual Premium",
        image: "/images/nam-ao-polo.jpg",
        price: 249000,
        oldPrice: 289000,
        discount: 14,
        rating: 4.8,
        reviews: 156,
        label: "OUTLET",
        colors: [
          { code: "#222", name: "Đen" },
          { code: "#fff", name: "Trắng" },
        ],
      },
    ]
  },
];

export default function CategoryProductsList() {
  return (
    <div className="max-w-7xl mx-auto px-4">
      {categories.map((category) => (
        <CategoryProducts
          key={category.id}
          title={category.title}
          products={category.products}
          category={category.id}
        />
      ))}
    </div>
  );
} 